---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  name: random8
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 1
  maxTrialCount: 1
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: num-layers
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "5"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
          - ftrl
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: numberLayers
        description: Number of training model layers
        reference: num-layers
      - name: optimizer
        description: Training model optimizer (sdg, adam or ftrl)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist:latest
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--num-layers=${trialParameters.numberLayers}"
                  - "--optimizer=${trialParameters.optimizer}"
            restartPolicy: Never
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   generateName: app-slack-notification-
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       containers:
#         - name: slack-notification
#           image: curlimages/curl
#           command:
#             - "curl"
#             - "-X"
#             - "POST"
#             - "--data-urlencode"
#             - 'payload={"channel": "#somechannel", "username": "hello", "text": "App Sync succeeded", "icon_emoji": ":ghost:"}'
#             - "https://hooks.slack.com/services/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"
#       restartPolicy: Never
#   backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    katib.kubeflow.org/experiment: random8
spec:
  template:
    spec:
      containers:
        - name: slack-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "--data-urlencode"
            - 'payload={"channel": "#somechannel", "username": "hello", "text": "App Sync succeeded", "icon_emoji": ":ghost:"}'
            - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2
