apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          args:
            - --namespace
            - argo
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: katib-experiment-
              spec:
                entrypoint: katib-experiment-with-slack-noti
                templates:
                  - name: katib-experiment-with-slack-noti
                    steps:
                      - - name: create-katib-experiment
                          template: katib-experiment
                      - - name: send-slack-message
                          template: slack-noti
                          arguments:
                            parameters:
                              - name: experiment-name
                                value: "{{steps.create-katib-experiment.outputs.parameters.generated-experiment-name}}"
                              - name: validation-accuracy
                                value: "{{steps.create-katib-experiment.outputs.parameters.validation-accuracy}}"
                              - name: train-accuracy
                                value: "{{steps.create-katib-experiment.outputs.parameters.train-accuracy}}"
                              - name: lr
                                value: "{{steps.create-katib-experiment.outputs.parameters.lr}}"
                              - name: num-layers
                                value: "{{steps.create-katib-experiment.outputs.parameters.num-layers}}"
                              - name: optimizer
                                value: "{{steps.create-katib-experiment.outputs.parameters.optimizer}}"
                  - name: katib-experiment
                    resource:
                      action: create
                      successCondition: status.trialsSucceeded=3
                      manifest: |
                        apiVersion: kubeflow.org/v1beta1
                        kind: Experiment
                        metadata:
                          generateName: random-
                        spec:
                          objective:
                            type: maximize
                            goal: 0.99
                            objectiveMetricName: Validation-accuracy
                            additionalMetricNames:
                              - Train-accuracy
                          algorithm:
                            algorithmName: random
                          parallelTrialCount: 3
                          maxTrialCount: 3
                          maxFailedTrialCount: 3
                          parameters:
                            - name: lr
                              parameterType: double
                              feasibleSpace:
                                min: "0.01"
                                max: "0.03"
                            - name: num-layers
                              parameterType: int
                              feasibleSpace:
                                min: "2"
                                max: "5"
                            - name: optimizer
                              parameterType: categorical
                              feasibleSpace:
                                list:
                                  - sgd
                                  - adam
                                  - ftrl
                          trialTemplate:
                            primaryContainerName: training-container
                            trialParameters:
                              - name: learningRate
                                description: Learning rate for the training model
                                reference: lr
                              - name: numberLayers
                                description: Number of training model layers
                                reference: num-layers
                              - name: optimizer
                                description: Training model optimizer (sdg, adam or ftrl)
                                reference: optimizer
                            trialSpec:
                              apiVersion: batch/v1
                              kind: Job
                              spec:
                                template:
                                  metadata:
                                    annotations:
                                      sidecar.istio.io/inject: "false"
                                  spec:
                                    containers:
                                      - name: training-container
                                        image: docker.io/kubeflowkatib/mxnet-mnist:latest
                                        command:
                                          - "python3"
                                          - "/opt/mxnet-mnist/mnist.py"
                                          - "--batch-size=64"
                                          - "--lr=${trialParameters.learningRate}"
                                          - "--num-layers=${trialParameters.numberLayers}"
                                          - "--optimizer=${trialParameters.optimizer}"
                                    restartPolicy: Never
                    outputs:
                      parameters:
                        - name: generated-experiment-name
                          valueFrom:
                            jsonPath: "{.metadata.name}"
                        - name: validation-accuracy
                          valueFrom:
                            jsonPath: "{.status.currentOptimalTrial.observation.metrics[0].latest}"
                        - name: train-accuracy
                          valueFrom:
                            jsonPath: "{.status.currentOptimalTrial.observation.metrics[1].latest}"
                        - name: lr
                          valueFrom:
                            jsonPath: "{.status.currentOptimalTrial.parameterAssignments[0].value}"
                        - name: num-layers
                          valueFrom:
                            jsonPath: "{.status.currentOptimalTrial.parameterAssignments[1].value}"
                        - name: optimizer
                          valueFrom:
                            jsonPath: "{.status.currentOptimalTrial.parameterAssignments[2].value}"
                  - name: slack-noti
                    inputs:
                      parameters:
                        - name: experiment-name
                        - name: validation-accuracy
                        - name: train-accuracy
                        - name: lr
                        - name: num-layers
                        - name: optimizer
                    container:
                      image: curlimages/curl
                      command: [sh, -c]
                      args: [
                          'curl -X POST -H -g "Content-Type: application/json" -d ''{
                          "blocks": [
                          {
                          "type": "section",
                          "text": {
                          "type": "mrkdwn",
                          "text": "<!channel> Experiment *{{inputs.parameters.experiment-name}}* Ended \n "
                          }
                          },
                          {
                          "type": "section",
                          "block_id": "section567",
                          "text": {
                          "type": "mrkdwn",
                          "text": "*Best Trial Info* \n \n Score: \n Validation Accuracy: {{inputs.parameters.validation-accuracy}}, Train Accuracy: {{inputs.parameters.train-accuracy}} \n \n Parameters: \n lr: {{inputs.parameters.lr}}, num-layers: {{inputs.parameters.num-layers}}, optimizer: {{inputs.parameters.optimizer}}"
                          },
                          "accessory": {
                          "type": "button",
                          "text": {
                          "type": "plain_text",
                          "text": "Check \n Experiment",
                          "emoji": true
                          },
                          "value": "click_me_567",
                          "url": "https://ysflow.com/_/katib/experiment/{{inputs.parameters.experiment-name}}?ns=argo",
                          "action_id": "button-action"
                          }
                          }
                          ]
                          }''
                          https://hooks.slack.com/services/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',
                        ]
