apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  generateName: random-year-
spec:
  metricsCollectorSpec:
    collector:
      kind: StdOut
    source:
      filter:
        metricsFormat:
          - "([\\w|-]+)\\s*:\\s*([+-]?\\d*(\\.\\d+)?([Ee][+-]?\\d+)?)"
  objective:
    type: minimize
    goal: 0.99
    objectiveMetricName: Validation-rmse
    additionalMetricNames:
      - Train-rmse
  algorithm:
    algorithmName: random
  parallelTrialCount: 1
  maxTrialCount: 8
  maxFailedTrialCount: 3
  parameters:
    - name: learning-rate
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "0.01"
    - name: num-leave
      parameterType: int
      feasibleSpace:
        min: "30"
        max: "40"
    - name: lambda-l1
      parameterType: double
      feasibleSpace:
        min: "0.7"
        max: "0.9"
    - name: lambda-l2
      parameterType: double
      feasibleSpace:
        min: "0.9"
        max: "1.0"
    - name: featrue-fraction
      parameterType: double
      feasibleSpace:
        min: "0.6"
        max: "0.7"
    - name: bagging-fraction
      parameterType: double
      feasibleSpace:
        min: "0.6"
        max: "0.9"
    - name: min-child-sample
      parameterType: int
      feasibleSpace:
        min: "6"
        max: "10"
    - name: min-child-weight
      parameterType: double
      feasibleSpace:
        min: "10.0"
        max: "40.0"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: learning-rate
      - name: num-leave
        description: reg
        reference: num-leave
      - name: lambdaL1
        description: reg
        reference: lambda-l1
      - name: lambdaL2
        description: reg
        reference: lambda-l2
      - name: featrueFraction
        description: reg
        reference: featrue-fraction
      - name: baggingFraction
        description: reg
        reference: bagging-fraction
      - name: minChildSample
        description: reg
        reference: min-child-sample
      - name: minChildWeight
        description: reg
        reference: min-child-weight
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: hahajong/lgbm-katib:year-data
                command:
                  - "python"
                  - "/app/lgbm.py"
                  - "--learning-rate=${trialParameters.learningRate}"
                  - "--num-leave=${trialParameters.num-leave}"
                  - "--lambda-l1=${trialParameters.lambdaL1}"
                  - "--lambda-l2=${trialParameters.lambdaL2}"
                  - "--featrue-fraction=${trialParameters.featrueFraction}"
                  - "--bagging-fraction=${trialParameters.baggingFraction}"
                  - "--min-child-sample=${trialParameters.minChildSample}"
                  - "--min-child-weight=${trialParameters.minChildWeight}"
                envFrom:
                  - secretRef:
                      name: s3-credential
            restartPolicy: Never
