apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: startup-pj
  namespace: seldon-deploy
spec:
  replicas: 1
  name: ensemble-deployment
  predictors:
    - componentSpecs:
        - spec:
            volumes:
              - name: model-provision-location
                emptyDir: {}
            initContainers:
              - name: model-initializer-1
                image: kfserving/storage-initializer:v0.6.1
                args:
                  - "s3://team06/mlflow/mlflow/artifacts/0/00eac01d95a746a88c619e15301bd0a2/artifacts/model"
                  - "/mnt/models/model-1"
                volumeMounts:
                  - mountPath: /mnt/models/model-1
                    name: model-provision-location
                envFrom:
                  - secretRef:
                      name: seldon-init-container-secret

              - name: model-initializer-2
                image: kfserving/storage-initializer:v0.6.1
                args:
                  - "s3://team06/mlflow/mlflow/artifacts/0/c73526d29eac48fd84b1b209a37f9d03/artifacts/model"
                  - "/mnt/models/model-2"
                volumeMounts:
                  - mountPath: /mnt/models/model-2
                    name: model-provision-location
                envFrom:
                  - secretRef:
                      name: seldon-init-container-secret

            containers:
              - name: year-trained-model
                image: seldonio/xgboostserver:1.14.0
                volumeMounts:
                  - mountPath: /mnt/models/model-1
                    name: model-provision-location
                    readOnly: true
                securityContext:
                  privileged: true
                  runAsUser: 0
                  runAsGroup: 0
                env:
                  - name: MODEL_METADATA
                    value: |
                      ---
                      name: model
                      inputs:
                      - messagetype: ndarray
                        schema:
                          names: [passenger_count, trip_distance, PULocationID, DOLocationID,payment_type, dayofweek, hour, minutes, time_diff]
                          shape: [ 8 ]
                      outputs:
                      - messagetype: ndarray
                        schema:
                          names: [fare-amount]
                          shape: [ 1 ]

              - name: new-model
                image: seldonio/xgboostserver:1.14.0
                volumeMounts:
                  - mountPath: /mnt/models/model-2
                    name: model-provision-location
                    readOnly: true
                securityContext:
                  privileged: true
                  runAsUser: 0
                  runAsGroup: 0
                env:
                  - name: MODEL_METADATA
                    value: |
                      ---
                      name: model
                      inputs:
                      - messagetype: ndarray
                        schema:
                          names: [passenger_count, trip_distance, PULocationID, DOLocationID,payment-type, dayofweek, hour, minutes, time_diff]
                          shape: [ 8 ]
                      outputs:
                      - messagetype: ndarray
                        schema:
                          names: [fare-amount]
                          shape: [ 1 ]

              - name: combiner
                image: hahajong/combiner:0.2
                env:
                  - name: MODEL_METADATA
                    value: |
                      ---
                      name: ensemble
                      inputs:
                      - messagetype: ndarray
                        schema:
                          names: [ensemble-input]
                          shape: [ 1 ]
                      outputs:
                      - messagetype: ndarray
                        schema:
                          names: [ensemble-output]
                          shape: [ 1 ]

              - name: inputtransformer
                image: hahajong/inputtransformer:0.3
                env:
                  - name: MODEL_METADATA
                    value: |
                      ---
                      name: preprocessor
                      inputs:
                      - messagetype: ndarray
                        schema:
                          names: [passenger_count, trip_distance, PULocation, DOLocation, payment_type, PUdatetime, time_diff]
                          shape: [ 7 ]
                      outputs:
                      - messagetype: ndarray
                        schema:
                          names: [passenger_count, trip_distance, PULocationID, DOLocationID, payment_type, dayofweek, hour, minutes, time_diff]
                          shape: [ 8 ]

      graph:
        children:
          - children:
              - children: []
                name: year-trained-model
                type: MODEL
                parameters:
                  - name: model_uri
                    type: STRING
                    value: "/mnt/models/model-1"
                endpoint:
                  type: REST
              - children: []
                name: new-model
                type: MODEL
                parameters:
                  - name: model_uri
                    type: STRING
                    value: "/mnt/models/model-2"
                endpoint:
                  type: REST
            name: combiner
            type: COMBINER
            endpoint:
              type: REST
        name: inputtransformer
        type: TRANSFORMER
        endpoint:
          type: REST
      name: ensemble-deployment
