apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: startup-pj
  namespace: seldon-deploy
spec:
  replicas: 1
  name: ensemble-deployment
  predictors:
    - componentSpecs:
        - hpaSpec:
            maxReplicas: 30
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 50
                type: Resource
            minReplicas: 1
          spec:
            volumes:
              - name: model-provision-location
                emptyDir: {}
            initContainers:
              - name: model-initializer-1
                image: kfserving/storage-initializer:v0.6.1
                args:
                  - "s3://team06/mlflow/mlflow/artifacts/0/8ebe06fa9a654ad4b13f4dc8692fc029/artifacts/model"
                  - "/mnt/models/model-1"
                volumeMounts:
                  - mountPath: /mnt/models/model-1
                    name: model-provision-location
                envFrom:
                  - secretRef:
                      name: seldon-init-container-secret

              - name: model-initializer-2
                image: kfserving/storage-initializer:v0.6.1
                args:
                  - "s3://team06/mlflow/mlflow/artifacts/0/c956d6525f1c4ad49a8f1b8918f6be78/artifacts/model"
                  - "/mnt/models/model-2"
                volumeMounts:
                  - mountPath: /mnt/models/model-2
                    name: model-provision-location
                envFrom:
                  - secretRef:
                      name: seldon-init-container-secret

            containers:
              - name: model-1
                image: seldonio/xgboostserver:1.14.0
                volumeMounts:
                  - mountPath: /mnt/models/model-1
                    name: model-provision-location
                    readOnly: true
                securityContext:
                  privileged: true
                  runAsUser: 0
                  runAsGroup: 0

              - name: model-2
                image: seldonio/xgboostserver:1.14.0
                volumeMounts:
                  - mountPath: /mnt/models/model-2
                    name: model-provision-location
                    readOnly: true
                securityContext:
                  privileged: true
                  runAsUser: 0
                  runAsGroup: 0

              - name: combiner
                image: hahajong/combiner:0.2

      graph:
        children:
          - children: []
            name: model-1
            type: MODEL
            parameters:
              - name: model_uri
                type: STRING
                value: "/mnt/models/model-1"
            endpoint:
              type: REST
          - children: []
            name: model-2
            type: MODEL
            parameters:
              - name: model_uri
                type: STRING
                value: "/mnt/models/model-2"
            endpoint:
              type: REST
        name: combiner
        type: COMBINER
        endpoint:
          type: REST
      name: ensemble-deployment
