apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-example
  namespace: seldon-deploy
spec:
  name: model
  predictors:
    - name: model

      componentSpecs:
        - spec:
            volumes:
              - name: model-provision-location
                emptyDir: {}

            initContainers:
              - name: model-initializer
                image: kfserving/storage-initializer:v0.6.1
                args:
                  - "s3://team06/mlflow/mlflow/artifacts/0/8ebe06fa9a654ad4b13f4dc8692fc029/artifacts/model"
                  - "/mnt/models"
                volumeMounts:
                  - mountPath: /mnt/models
                    name: model-provision-location
                envFrom:
                  - secretRef:
                      name: seldon-init-container-secret

            containers:
              - name: model
                image: seldonio/xgboostserver:1.14.0
                volumeMounts:
                  - mountPath: /mnt/models
                    name: model-provision-location
                    readOnly: true
                securityContext:
                  privileged: true
                  runAsUser: 0
                  runAsGroup: 0

      graph:
        name: model
        type: MODEL
        parameters:
          - name: model_uri
            type: STRING
            value: "/mnt/models"
        children: []
