name: Python application

on:
  push:
    branches: [experiment]
    paths:
      - data/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: experiment
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: hahajong/xgb-katib
          tags: ${{ github.sha }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create Pull Request to dev
        uses: peter-evans/create-pull-request@v4
        with:
          branch: dev
